# Generated by Django 5.0.6 on 2024-06-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('courriel', models.EmailField(max_length=255)),
                ('motDePasse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('idPrestataire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=255)),
                ('courriel', models.EmailField(max_length=255)),
                ('motDePasse', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'prestataire',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('idDemande', models.AutoField(primary_key=True, serialize=False)),
                ('numeroDemande', models.CharField(max_length=255)),
                ('dateDemande', models.DateField()),
                ('statut', models.CharField(max_length=255)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.client')),
                ('idPrestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.prestataire')),
            ],
            options={
                'db_table': 'demande',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('idEvaluation', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('idDemande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.demande')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.IntegerField()),
                ('categorie', models.CharField(max_length=255)),
                ('idPrestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.prestataire')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AddField(
            model_name='demande',
            name='idService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.service'),
        ),
    ]
