# Generated by Django 4.2.13 on 2024-06-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('idDemande', models.AutoField(primary_key=True, serialize=False)),
                ('numeroDemande', models.CharField(max_length=255)),
                ('dateDemande', models.DateField()),
                ('statut', models.CharField(max_length=255)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.client')),
            ],
            options={
                'db_table': 'demandes',
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('idPrestataire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'prestataires',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.IntegerField()),
                ('categorie', models.CharField(max_length=255)),
                ('idPrestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.prestataire')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('idEvaluation', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('idDemande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.demande')),
            ],
            options={
                'db_table': 'evaluations',
            },
        ),
        migrations.AddField(
            model_name='demande',
            name='idPrestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.prestataire'),
        ),
        migrations.AddField(
            model_name='demande',
            name='idService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClient.service'),
        ),
    ]
