# Generated by Django 4.2.13 on 2024-06-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appClient', '0002_client_groups_client_is_staff_client_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='username',
        ),
    ]
