# Generated by Django 4.2.13 on 2024-06-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appClient', '0003_rename_email_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestataire',
            old_name='email',
            new_name='username',
        ),
    ]
