# Generated by Django 5.0.6 on 2024-06-09 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='idPrestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appService.prestataire'),
        ),
    ]
